version: "3.8"
services:
  db:
    env_file: .env
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    env_file: .env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  pgdata:
