# Generated by Django 3.0.8 on 2020-07-02 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template_text',
            field=models.TextField(default='*** FORNEÇA UM TEXTO PARA TEMPLATE DA CAMPANHA ***', verbose_name='Template para telegrama, fax, email'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto do argumento')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Campaign', verbose_name='Campanha')),
            ],
        ),
    ]
